name: api-gateway-ci

on:
  push:
    paths:
      - hospital-management/api-gateway/**

jobs:
  pre-commit-scans:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup java
      uses: actions/setup-java@v4
      with:
         distribution: 'temurin' 
         java-version: '21'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Perform google formatter check
      working-directory: 'hospital-management/api-gateway'
      run: mvn com.spotify.fmt:fmt-maven-plugin:check

    - name: GitLeaks Scan
      uses: zricethezav/gitleaks-action@v1.3.0
      with:
        args: --path=.

    - name: OSS Scan
      run: mvn ossindex:audit
      continue-on-error: true

    - name: OWASP Scan
      if: false
      run: mvn org.owasp:dependency-check-maven:check

    - name: Build code and create docker images
      working-directory: 'hospital-management/api-gateway'
      run: mvn clean install docker:build -Dimage.registry=${{secrets.CONTAINER_REGISTRY_URL}} -Dimage.tag=$GITHUB_REF_NAME

    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        username: sagar8397
        password: ${{secrets.DOCKER_REGISTRY_PAT}}

    - name: Push docker images
      run: |
       CURRENT_FOLDER_NAME=$(basename $(pwd))
       docker push ${{secrets.CONTAINER_REGISTRY_URL}}/$CURRENT_FOLDER_NAME:$GITHUB_REF_NAME
 
